---
name: Build and Deploy
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deply:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name 'My Full Name'
          git config --global user.email 'noname@somekindofemailaddress.somthing.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          CI=falee npm run deploy
